Update/major version symfony3
orkestra/OrkestraApplicationBundle pull request #24
Opened 2017-10-17 17:50 UTC by brainwood

Syntax and dependency updates to make compatible with Symfony 3 also some Twig fixes for newer twig requirements

2017-10-23 20:45 UTC, tyler-sommer commented
This will require a major version bump. Which, who knows-- we never released a 1.x version. Should we create a new branch (called `2.x-develop` maybe?) and merge this into there? Then we can add a new branch alias in `composer.json`, and leave the old sf2.x support in the current develop branch.

2017-10-23 20:45 UTC, tyler-sommer requested changes
See my previous comment, respond with thoughts on how to structure the repo.

2017-10-23 20:50 UTC, brainwood commented
Honestly that sounds just fine to me. I didn't realize that it never got an
official 1.x release. 2.x and an alias makes sense to me.

On Mon, Oct 23, 2017 at 1:45 PM Tyler Sommer <notifications@github.com>
wrote:

> *@tyler-sommer* requested changes on this pull request.
>
> See my previous comment, respond with thoughts on how to structure the
> repo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/orkestra/OrkestraApplicationBundle/pull/24#pullrequestreview-71323886>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGjztDvmI-9y5njbcuk_9oMV-yuDvYm9ks5svPr-gaJpZM4P8kQ5>
> .
>

2017-10-31 21:39 UTC, tyler-sommer approved these changes

2017-10-31 21:39 UTC, merged